### ISSUE TITLE
Support for ubuntu 21.04

### ISSUE THREAD

**Issue by poussa** [osism/openstack-k8s-capi-images#13]
What would it take to support later ubuntu version or newer kernel, e.g., ubuntu2104 and/or kernel 5.11+ ?

I assume somebody needs to work on the image builder upstream to enable such things...

**Comment by berendt** [comment]
Exactly. We only use https://github.com/kubernetes-sigs/image-builder here to build the images. There is only Ubuntu 18.04 and Ubuntu 20.04 in there right now. Think it will be difficult to place 21.04 there because it is not an LTS.

Would flatcar images help you? Is there kernel 5.11.x in there?

**Comment by berendt** [comment]
@poussa Stable/Beta/Alpha flatcar is using kernel 5.10.38.

**Comment by poussa** [comment]
I am not familiar with flatcar images. Can I use them with capi open stack provider? And even if I can, 5.11 is not quite there.

**Comment by berendt** [comment]
@poussa I'll see how much effort it takes to build an Ubuntu 21.04. Maybe it works directly.

**Comment by berendt** [comment]
We have chosen to build only the distributions that are available upstream.
